server.modules = (
  "mod_dirlisting",
  "mod_webdav"
)

server.bind = "0.0.0.0"
server.document-root = "/www"
server.use-ipv6 = "enable"

dir-listing.activate = "enable"
dir-listing.encoding = "utf-8"
dir-listing.hide-dotfiles = "disable"

webdav.activate = "enable"
webdav.is-readonly = "enable"
